// Auto-generated by rebuild_report_data.py — do not edit by hand.
const adiposeBands = [
  {
    "band": "Chr9:56-60Mb",
    "n_genes": 31,
    "pc1": 68.5,
    "random_pc1": 22.6,
    "ratio": 3.03,
    "meanAbsR": 0.666,
    "driver": "Aox3",
    "driverLogp": 25.5
  },
  {
    "band": "Chr6:12-16Mb",
    "n_genes": 10,
    "pc1": 61.1,
    "random_pc1": 20.4,
    "ratio": 2.99,
    "meanAbsR": 0.561,
    "driver": "Tmem178a",
    "driverLogp": 81.6
  },
  {
    "band": "Chr1:228-232Mb",
    "n_genes": 8,
    "pc1": 68.3,
    "random_pc1": 24.0,
    "ratio": 2.84,
    "meanAbsR": 0.594,
    "driver": "",
    "driverLogp": null
  },
  {
    "band": "Chr5:68-72Mb",
    "n_genes": 73,
    "pc1": 65.8,
    "random_pc1": 24.5,
    "ratio": 2.69,
    "meanAbsR": 0.635,
    "driver": "Slc44a1",
    "driverLogp": 6.6
  },
  {
    "band": "Chr1:60-64Mb",
    "n_genes": 8,
    "pc1": 74.2,
    "random_pc1": 28.7,
    "ratio": 2.58,
    "meanAbsR": 0.703,
    "driver": "Vom2r16",
    "driverLogp": 61.4
  },
  {
    "band": "Chr12:44-48Mb",
    "n_genes": 39,
    "pc1": 64.9,
    "random_pc1": 28.0,
    "ratio": 2.32,
    "meanAbsR": 0.626,
    "driver": "",
    "driverLogp": null
  },
  {
    "band": "Chr20:16-20Mb",
    "n_genes": 8,
    "pc1": 68.0,
    "random_pc1": 29.5,
    "ratio": 2.3,
    "meanAbsR": 0.619,
    "driver": "",
    "driverLogp": null
  },
  {
    "band": "Chr2:204-208Mb",
    "n_genes": 9,
    "pc1": 60.6,
    "random_pc1": 26.5,
    "ratio": 2.29,
    "meanAbsR": 0.554,
    "driver": "Gpr88",
    "driverLogp": 16.6
  },
  {
    "band": "Chr5:116-124Mb",
    "n_genes": 35,
    "pc1": 51.9,
    "random_pc1": 26.5,
    "ratio": 1.96,
    "meanAbsR": 0.462,
    "driver": "Rab3b",
    "driverLogp": 44.7
  },
  {
    "band": "Chr2:184-192Mb",
    "n_genes": 33,
    "pc1": 61.5,
    "random_pc1": 32.9,
    "ratio": 1.87,
    "meanAbsR": 0.588,
    "driver": "Olfml3",
    "driverLogp": 29.4
  },
  {
    "band": "Chr20:36-40Mb",
    "n_genes": 12,
    "pc1": 71.1,
    "random_pc1": 41.6,
    "ratio": 1.71,
    "meanAbsR": 0.681,
    "driver": "Nt5dc1",
    "driverLogp": 28.7
  },
  {
    "band": "Chr4:132-136Mb",
    "n_genes": 10,
    "pc1": 39.8,
    "random_pc1": 23.8,
    "ratio": 1.67,
    "meanAbsR": 0.299,
    "driver": "",
    "driverLogp": null
  },
  {
    "band": "Chr18:20-24Mb",
    "n_genes": 9,
    "pc1": 47.3,
    "random_pc1": 37.5,
    "ratio": 1.26,
    "meanAbsR": 0.374,
    "driver": "",
    "driverLogp": null
  }
];

const liverBands = [
  {
    "band": "Chr1:52-56Mb",
    "n_genes": 9,
    "pc1": 64.2,
    "random_pc1": 23.5,
    "ratio": 2.74,
    "meanAbsR": 0.593,
    "driver": "",
    "driverLogp": null
  },
  {
    "band": "Chr7:120-124Mb",
    "n_genes": 26,
    "pc1": 51.2,
    "random_pc1": 22.2,
    "ratio": 2.31,
    "meanAbsR": 0.478,
    "driver": "Abcd2",
    "driverLogp": 20.4
  },
  {
    "band": "Chr1:140-144Mb",
    "n_genes": 10,
    "pc1": 50.4,
    "random_pc1": 22.8,
    "ratio": 2.21,
    "meanAbsR": 0.432,
    "driver": "Tmem135",
    "driverLogp": 6.1
  },
  {
    "band": "Chr5:28-32Mb",
    "n_genes": 7,
    "pc1": 62.0,
    "random_pc1": 33.9,
    "ratio": 1.83,
    "meanAbsR": 0.519,
    "driver": "Calb1",
    "driverLogp": 12.9
  },
  {
    "band": "Chr4:168-172Mb",
    "n_genes": 24,
    "pc1": 55.2,
    "random_pc1": 31.9,
    "ratio": 1.73,
    "meanAbsR": 0.515,
    "driver": "Arhgdib",
    "driverLogp": 9.3
  },
  {
    "band": "Chr4:176-184Mb",
    "n_genes": 55,
    "pc1": 48.4,
    "random_pc1": 32.7,
    "ratio": 1.48,
    "meanAbsR": 0.459,
    "driver": "Rassf8",
    "driverLogp": 19.5
  },
  {
    "band": "Chr1:148-152Mb",
    "n_genes": 26,
    "pc1": 44.1,
    "random_pc1": 31.1,
    "ratio": 1.42,
    "meanAbsR": 0.384,
    "driver": "",
    "driverLogp": null
  },
  {
    "band": "Chr6:24-28Mb",
    "n_genes": 13,
    "pc1": 44.1,
    "random_pc1": 38.4,
    "ratio": 1.15,
    "meanAbsR": 0.369,
    "driver": "Krtcap3",
    "driverLogp": 66.6
  }
];

const enrichmentSummary = [
  {
    "tissue": "adipose",
    "band": "Chr5:68-72Mb",
    "n_genes": 73,
    "tier": "reliable (>=30 genes)",
    "n_terms": 14,
    "best_p": 1.5509800848917387e-05,
    "top_term": "regulation of RNA metabolic process"
  },
  {
    "tissue": "adipose",
    "band": "Chr2:184-192Mb",
    "n_genes": 33,
    "tier": "reliable (>=30 genes)",
    "n_terms": 1,
    "best_p": 0.010640063865385827,
    "top_term": "Protein processing in endoplasmic reticulum"
  },
  {
    "tissue": "adipose",
    "band": "Chr12:44-48Mb",
    "n_genes": 39,
    "tier": "reliable (>=30 genes)",
    "n_terms": 0,
    "best_p": null,
    "top_term": ""
  },
  {
    "tissue": "adipose",
    "band": "Chr5:116-124Mb",
    "n_genes": 35,
    "tier": "reliable (>=30 genes)",
    "n_terms": 0,
    "best_p": null,
    "top_term": ""
  },
  {
    "tissue": "adipose",
    "band": "Chr9:56-60Mb",
    "n_genes": 31,
    "tier": "reliable (>=30 genes)",
    "n_terms": 0,
    "best_p": null,
    "top_term": ""
  },
  {
    "tissue": "adipose",
    "band": "Chr20:36-40Mb",
    "n_genes": 12,
    "tier": "marginal (10-29 genes)",
    "n_terms": 0,
    "best_p": null,
    "top_term": ""
  },
  {
    "tissue": "adipose",
    "band": "Chr4:132-136Mb",
    "n_genes": 10,
    "tier": "marginal (10-29 genes)",
    "n_terms": 0,
    "best_p": null,
    "top_term": ""
  },
  {
    "tissue": "adipose",
    "band": "Chr6:12-16Mb",
    "n_genes": 10,
    "tier": "marginal (10-29 genes)",
    "n_terms": 0,
    "best_p": null,
    "top_term": ""
  },
  {
    "tissue": "liver",
    "band": "Chr4:176-184Mb",
    "n_genes": 55,
    "tier": "reliable (>=30 genes)",
    "n_terms": 1,
    "best_p": 0.0007588049788942109,
    "top_term": "Steroid biosynthesis"
  },
  {
    "tissue": "liver",
    "band": "Chr7:120-124Mb",
    "n_genes": 26,
    "tier": "marginal (10-29 genes)",
    "n_terms": 0,
    "best_p": null,
    "top_term": ""
  },
  {
    "tissue": "liver",
    "band": "Chr1:148-152Mb",
    "n_genes": 26,
    "tier": "marginal (10-29 genes)",
    "n_terms": 0,
    "best_p": null,
    "top_term": ""
  },
  {
    "tissue": "liver",
    "band": "Chr4:168-172Mb",
    "n_genes": 24,
    "tier": "marginal (10-29 genes)",
    "n_terms": 0,
    "best_p": null,
    "top_term": ""
  },
  {
    "tissue": "liver",
    "band": "Chr6:24-28Mb",
    "n_genes": 13,
    "tier": "marginal (10-29 genes)",
    "n_terms": 0,
    "best_p": null,
    "top_term": ""
  },
  {
    "tissue": "liver",
    "band": "Chr1:140-144Mb",
    "n_genes": 10,
    "tier": "marginal (10-29 genes)",
    "n_terms": 0,
    "best_p": null,
    "top_term": ""
  }
];

const adiposePerBandPlots = ["adipose_band_chr12_44_48Mb.html", "adipose_band_chr16_68_72Mb.html", "adipose_band_chr18_20_24Mb.html", "adipose_band_chr1_228_232Mb.html", "adipose_band_chr1_60_64Mb.html", "adipose_band_chr20_16_20Mb.html", "adipose_band_chr20_36_40Mb.html", "adipose_band_chr2_184_192Mb.html", "adipose_band_chr2_204_208Mb.html", "adipose_band_chr4_132_136Mb.html", "adipose_band_chr5_116_124Mb.html", "adipose_band_chr5_68_72Mb.html", "adipose_band_chr6_12_16Mb.html", "adipose_band_chr9_56_60Mb.html"];

const liverPerBandPlots = ["liver_band_chr1_140_144Mb.html", "liver_band_chr1_148_152Mb.html", "liver_band_chr1_228_232Mb.html", "liver_band_chr1_52_56Mb.html", "liver_band_chr1_8_12Mb.html", "liver_band_chr4_168_172Mb.html", "liver_band_chr4_176_184Mb.html", "liver_band_chr5_100_104Mb.html", "liver_band_chr5_16_20Mb.html", "liver_band_chr5_28_32Mb.html", "liver_band_chr6_24_28Mb.html", "liver_band_chr7_120_124Mb.html", "liver_band_chr8_44_48Mb.html"];

function buildBarChart(divId, data, xKey, yKey, title, color) {
  const x = data.map(d => d.band);
  const y = data.map(d => d[yKey]);
  const hoverText = data.map(d =>
    `${d.band}<br>Genes: ${d.n_genes}<br>PC1: ${d.pc1}%<br>Candidate: ${d.driver || "none"}<br>Cis -logP: ${d.driverLogp ?? "N/A"}`
  );
  const trace = {
    x: x, y: y, type: "bar",
    marker: { color: color },
    text: y.map(v => v.toFixed ? v.toFixed(2) : v),
    textposition: "outside",
    hoverinfo: "text", hovertext: hoverText
  };
  const layout = {
    title: { text: title, font: { size: 14 } },
    margin: { l: 60, r: 20, t: 45, b: 80 },
    xaxis: { tickangle: -45 },
    yaxis: { title: yKey === "n_genes" ? "Genes in band" : "PC1 variance ratio" },
    paper_bgcolor: "rgba(0,0,0,0)", plot_bgcolor: "rgba(0,0,0,0)",
    font: { family: "-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, sans-serif" }
  };
  Plotly.newPlot(divId, [trace], layout, { responsive: true });
}

function buildCisTransChart() {
  const tissues = ["Adipose", "Liver"];
  const cis = [1463, 1058];
  const trans = [32191, 32596];
  const trace1 = { x: tissues, y: cis, name: "Cis eQTLs", type: "bar", marker: { color: "#2563eb" } };
  const trace2 = { x: tissues, y: trans, name: "Trans eQTLs", type: "bar", marker: { color: "#c0392b" } };
  const layout = {
    barmode: "group",
    title: { text: "Cis vs. trans eQTL counts", font: { size: 14 } },
    yaxis: { title: "Number of peaks", type: "log" },
    margin: { l: 60, r: 20, t: 45, b: 40 },
    paper_bgcolor: "rgba(0,0,0,0)", plot_bgcolor: "rgba(0,0,0,0)",
    font: { family: "-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, sans-serif" }
  };
  Plotly.newPlot("cis-trans-chart", [trace1, trace2], layout, { responsive: true });
}

function renderTable(tbodyId, rows, columns) {
  const tbody = document.getElementById(tbodyId);
  tbody.innerHTML = rows.map(row => {
    const cells = columns.map(col => {
      let val = row[col.key];
      if (col.key === "driverLogp" || col.key === "best_p") {
        val = val == null ? "—" : (val < 0.001 ? val.toExponential(2) : val.toFixed(4));
      } else if (col.key === "ratio" || col.key === "meanAbsR") {
        val = val.toFixed(2);
      } else if (col.key === "pc1" || col.key === "random_pc1") {
        val = val.toFixed(1) + "%";
      } else {
        val = val == null || val === "" ? "—" : val;
      }
      return `<td>${val}</td>`;
    }).join("");
    return `<tr>${cells}</tr>`;
  }).join("");
}

function setupSorting(tableId) {
  const table = document.getElementById(tableId);
  const headers = table.querySelectorAll("th");
  const tbody = table.querySelector("tbody");
  headers.forEach((th, idx) => {
    th.addEventListener("click", () => {
      const rows = Array.from(tbody.querySelectorAll("tr"));
      const dir = th.dataset.dir === "asc" ? -1 : 1;
      th.dataset.dir = dir === 1 ? "asc" : "desc";
      rows.sort((a, b) => {
        let av = a.children[idx].textContent.trim();
        let bv = b.children[idx].textContent.trim();
        const an = parseFloat(av.replace(/,/g, ""));
        const bn = parseFloat(bv.replace(/,/g, ""));
        if (!isNaN(an) && !isNaN(bn) && av !== "—" && bv !== "—") {
          return (an - bn) * dir;
        }
        return av.localeCompare(bv) * dir;
      });
      rows.forEach(r => tbody.appendChild(r));
    });
  });
}

function populateGallery() {
  const adiposeContainer = document.getElementById("adipose-band-gallery");
  const liverContainer = document.getElementById("liver-band-gallery");

  function makeCard(file) {
    const label = file
      .replace(/^(adipose|liver)_band_/, "")
      .replace(".html", "")
      .replace(/_/g, " ");
    return `
      <a class="gallery-item" href="../results/plots/${file}" target="_blank">
        <div class="thumb-title">${label}</div>
        <div class="thumb-desc">Zoomed Manhattan</div>
      </a>
    `;
  }

  adiposeContainer.innerHTML = adiposePerBandPlots.map(makeCard).join("");
  liverContainer.innerHTML = liverPerBandPlots.map(makeCard).join("");
}

document.addEventListener("DOMContentLoaded", () => {
  buildCisTransChart();
  buildBarChart("adipose-bands-chart", adiposeBands, "band", "n_genes", "Adipose trans-bands by gene count", "#c0392b");
  buildBarChart("liver-bands-chart", liverBands, "band", "n_genes", "Liver trans-bands by gene count", "#2563eb");
  buildBarChart("adipose-pc1-chart", adiposeBands, "band", "ratio", "Adipose band PC1 enrichment ratio", "#7b1fa2");
  buildBarChart("liver-pc1-chart", liverBands, "band", "ratio", "Liver band PC1 enrichment ratio", "#7b1fa2");

  renderTable("adipose-table-body", adiposeBands, [
    { key: "band" }, { key: "n_genes" }, { key: "pc1" }, { key: "random_pc1" },
    { key: "ratio" }, { key: "meanAbsR" }, { key: "driver" }, { key: "driverLogp" }
  ]);
  renderTable("liver-table-body", liverBands, [
    { key: "band" }, { key: "n_genes" }, { key: "pc1" }, { key: "random_pc1" },
    { key: "ratio" }, { key: "meanAbsR" }, { key: "driver" }, { key: "driverLogp" }
  ]);
  renderTable("enrichment-table-body", enrichmentSummary, [
    { key: "tissue" }, { key: "band" }, { key: "n_genes" }, { key: "tier" },
    { key: "n_terms" }, { key: "best_p" }, { key: "top_term" }
  ]);

  setupSorting("adipose-table");
  setupSorting("liver-table");
  setupSorting("enrichment-table");
  populateGallery();
});
